dist: bionic
language: c
addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    update: true
    packages:
      - liburiparser-dev
env:
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6
  - PGVERSION=10
  - PGVERSION=11
  - PGVERSION=12
script: |
  set -e
  PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
  sudo apt-get install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  sudo pg_createcluster --start $PGVERSION test -p 55435 -- -A trust
  make all
  sudo make install
  PGPORT=55435 make installcheck PGUSER=postgres
